### ISSUE TITLE
predict_y not defined?

### ISSUE THREAD

**Issue by Asasuser** [STOR-i/GaussianProcesses.jl#73] opened 2017-12-02 14:07 UTC
Hi! I am quite unfamiliar with julia, so this issue might have a simple solution that I overlooked.
When attempting to use this package for the first time on Juno IDE (with JuliaPro for windows, Julia version 0.5), I got the error message

> LoadError: UndefVarError: predict_y not defined

 which got me puzzled, since predict_y is a method already defined in the package. The code I was trying to execute was this, following a notebook example of regression:

`using Plots, GaussianProcesses, Distributions`
`logobsnoise=-1.0`
`Kern=SE(0.0,0.0)`
`X=2π*rand(Normal(),10)`
`Y=sin.(X)+.05*rand(10)`
`mu = MeanZero()`
`gp=GP(X,Y,mu,Kern,logobsnoise)`
`μ, σ² = predict_y(gp,linspace(0,2π,100));`
`plot(gp; xlabel="x", ylabel="y", title="Gaussian process", legend=false, fmt=:png)`

The necessary packages (Plots, GaussianProcesses, Distributions) were installed and updated. How can I fix this error message?

**Comment by maximerischard** [comment] 2017-12-02 16:32
That code should work with the latest version of the package. Can you check what version you have with `Pkg.status("GaussianProcesses")`? I'm guessing you have version 0.4 rather than 0.5. Before 0.5 `predict_y` was simply `predict`.

The problem is that we decided not to support julia v0.5 going forward. Julia v0.6 has been available since June, and we wanted to focus our time on improving the package rather than backwards compatibility. Are you able to upgrade to julia v0.6?

**Comment by Asasuser** [comment] 2017-12-02 22:54
You were right, my Julia was still in version 0.5. Now after the update the predict_y issue was resolved.  I got a different error though; using the same code, I got the message:

> LoadError: MethodError: no method matching GaussianProcesses.GP(::RowVector{Float64,Array{Float64,1}}, ::Array{Float64,1}, ::GaussianProcesses.MeanConst, ::GaussianProcesses.SEIso, ::Float64)
Closest candidates are:
  GaussianProcesses.GP(!Matched::Array{Float64,2}, ::Array{Float64,1}, ::GaussianProcesses.Mean, ::GaussianProcesses.Kernel, ::Float64) at C:\JuliaPro-0.6.1.1\pkgs-0.6.1.1\v0.6\GaussianProcesses\src\GP.jl:41
  GaussianProcesses.GP(!Matched::Array{Float64,1}, ::Array{Float64,1}, ::GaussianProcesses.Mean, ::GaussianProcesses.Kernel, ::Float64) at C:\JuliaPro-0.6.1.1\pkgs-0.6.1.1\v0.6\GaussianProcesses\src\GP.jl:53
  GaussianProcesses.GP(!Matched::Array{Float64,2}, ::Array{Float64,1}, ::GaussianProcesses.Mean, ::GaussianProcesses.Kernel) at C:\JuliaPro-0.6.1.1\pkgs-0.6.1.1\v0.6\GaussianProcesses\src\GP.jl:41

**Comment by maximerischard** [comment] 2017-12-02 23:36
I think this is a bug that we fixed in July: 5a7c7e5. Which makes me think you still have an older version of `GaussianProcesses.jl`. Could you run `Pkg.checkout("GaussianProcesses")`, restart julia, and try again? Sorry about this.

**Comment by Asasuser** [comment] 2017-12-03 02:53
Hi! I did as you suggested. upon doing Pkg.checkout("GaussianProcesses") and restarting, Julia complained that I didn't have the module "FastGausssianQuadrature" installed. When I tried adding the package I got the following error:

> 
Unsatisfiable requirements detected for package ForwardDiff:
├─version range [0.5.0,0.5.0+) set by an explicit requirement
├─version range [0.0.0-,∞) required by package ReverseDiffSparse, whose allowed version range is [0.8.0,0.8.0+):
│ ├─version range [0.8.0,0.8.0+) set by an explicit requirement
│ └─version range [0.8.0,0.9.0) required by package JuMP, whose allowed version range is [0.18.0,0.18.0+):
  │ └─version range [0.18.0,0.18.0+) set by an explicit requirement
├─version range [0.0.0-,∞) required by package Optim, whose allowed version range is [0.10.0,0.10.0+):
│ ├─version range [0.10.0,0.10.0+) set by an explicit requirement
│ ├─version range [0.7.0-0.8,∞) required by package GaussianProcesses, whose only allowed version is 0.5.0+:
│ │ ├─version 0.5.0+ set by fixed requirement (package is checked out, dirty or pinned)
│ │ └─version range [0.0.0-,∞) set by an explicit requirement
│ ├─version range [0.0.0-,∞) required by package QuantEcon, whose allowed version range is [0.14.0,0.14.0+):
│ │ └─version range [0.14.0,0.14.0+) set by an explicit requirement
│ └─version range [0.0.0-,∞) required by package KernelDensity, whose allowed version range is [0.3.2,0.3.2+):
  │ ├─version range [0.3.2,0.3.2+) set by an explicit requirement
  │ └─version range [0.0.0-,∞) required by package Gadfly, whose allowed version range is [0.6.4,0.6.4+):
    │ └─version range [0.6.4,0.6.4+) set by an explicit requirement
├─version range [0.0.0-,∞) required by package Roots, whose allowed version range is [0.4.1,0.4.1+):
│ ├─version range [0.4.1,0.4.1+) set by an explicit requirement
│ └─version range [0.0.0-,∞) required by package HypothesisTests, whose allowed version range is [0.6.0,0.6.0+):
  │ └─version range [0.6.0,0.6.0+) set by an explicit requirement
├─version range [0.0.0-,∞) required by package Klara, whose allowed version range is [0.9.2,∞):
│ └─version range [0.9.2,∞) required by package GaussianProcesses, whose only allowed version is 0.5.0+:
  │ └─[see above for GaussianProcesses backtrace]
├─version range [0.0.0-,∞) required by package Flux, whose allowed version range is [0.3.3,0.3.3+):
│ └─version range [0.3.3,0.3.3+) set by an explicit requirement
├─version range [0.0.0-,∞) required by package JuMP, whose allowed version range is [0.18.0,0.18.0+):
│ └─[see above for JuMP backtrace]
└─version range [0.3.4,0.5.0) or [0.6.0,∞) required by package ReverseDiff, whose allowed version range is [0.1.0,∞):
  └─version range [0.1.0,∞) required by package Klara, whose allowed version range is [0.9.2,∞):
    └─[see above for Klara backtrace]
The intersection of the requirements is empty.
filter_versions(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{AbstractString,Base.Pkg.Types.ResolveBacktraceItem}) at .\pkg\query.jl:299
prune_versions(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{AbstractString,Base.Pkg.Types.ResolveBacktraceItem}) at .\pkg\query.jl:328
prune_dependencies(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{AbstractString,Base.Pkg.Types.ResolveBacktraceItem}) at .\pkg\query.jl:546
resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at .\pkg\entry.jl:498
resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}) at .\pkg\entry.jl:479
edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet,N} where N) at .\pkg\entry.jl:30
(::Base.Pkg.Entry.##1#3{String,Base.Pkg.Types.VersionSet})() at .\task.jl:335
in add at base\pkg\pkg.jl:117
in #cd#1 at base\pkg\dir.jl:32
in withenv at base\env.jl:157
in cd at base\file.jl:59
in  at base\pkg\dir.jl:33
in add at base\pkg\entry.jl:51
in macro expansion at base\task.jl:303 <inlined>
in sync_end at base\task.jl:287

 


>

**Comment by Asasuser** [comment] 2017-12-03 02:56
I also tried updating the Package GaussianProcesses, and when I did, it gave me the message

> 
fixed packages introduce conflicting requirements for Klara: 
         GaussianProcesses requires versions [0.9.2,∞) [none of the available versions can satisfy this requirement]
       available versions are 0.6.0, 0.6.1, 0.7.0 and 0.7.1
in update at base\pkg\pkg.jl:228
in #cd#1 at base\pkg\dir.jl:32
in withenv at base\env.jl:157
in cd at base\file.jl:59
in  at base\pkg\dir.jl:33
in update at base\pkg\entry.jl:461
in resolve at base\pkg\entry.jl:496
in check_requirements at base\pkg\query.jl:222

**Comment by maximerischard** [comment] 2017-12-03 04:39
@chris-nemeth what's the deal with the FastGausssianQuadrature requirement? The dependency was introduced by commit 1677b4e619c3437fe73746fe24cb5676c4e7dbb7 9 months ago, but is capped at version 0.0.1, which was released in September 2015. The most recent version is 0.3.0. So, two question:
- what are we using FastGausssianQuadrature?
- why are we capping at version 0.0.1?

**Comment by maximerischard** [comment] 2017-12-03 05:08
@Asasuser I'm really sorry about this. Could you try `Pkg.checkout("GaussianProcesses", branch="newoptim")`? That will get code from a branch where I've (temporarily) removed the Klara and FastGausssianQuadrature requirements.

**Comment by chris-nemeth** [comment] 2017-12-03 07:32
FastGaussianQuadrature is used for 1D integration when using non-Gaussian likelihoods. I'm not sure why we capped the version it's probably not necessary. More generally, we should have another look at all of the dependencies again. We capped Optim after the developers informed us that beyond v0.8 there would be breaking changes, but these should be easy to resolve and something worth us now doing.

**Comment by Asasuser** [comment] 2017-12-20 02:13
Hi, good evening. Yeah, the error messages are gone now, although the plot does not appear when I run the code (or is it not supposed to be printed on screen?). The other lines of code seem to be working properly, as I can see that the input variable X and the output variable Y are defined in the workspace (so the method predict_y is working). The line
`plot(gp; xlabel="x", ylabel="y", title="Gaussian process", legend=false, fmt=:png)
`
does not seem to produce any output.

**Comment by maximerischard** [comment] 2018-03-02 11:57
The dependencies have been updated on the current master branch. New package version to come.

**Closed by maximerischard** 2018-03-02 11:57 UTC
